-- Customers
CREATE TABLE "customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "city" varchar,
  "preferences" jsonb
);


-- Products
CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "category" varchar,
  "price" decimal
);

-- Orders
CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "order_date" date DEFAULT CURRENT_DATE,
  "total" decimal,
  CONSTRAINT fk_orders_customer FOREIGN KEY ("customer_id") REFERENCES "customers" ("id")
);

-- Order Items
CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int,
  "subtotal" decimal,
  CONSTRAINT fk_orderitems_order FOREIGN KEY ("order_id") REFERENCES "orders" ("id"),
  CONSTRAINT fk_orderitems_product FOREIGN KEY ("product_id") REFERENCES "products" ("id"),
  CONSTRAINT orderitems_orderid_productid_unique UNIQUE ("order_id", "product_id")
);

-- Products_Order_Items (join tambahan)
CREATE TABLE "products_order_items" (
  "products_id" int,
  "order_items_id" int,
  PRIMARY KEY ("products_id", "order_items_id"),
  CONSTRAINT fk_products_orderitems_product FOREIGN KEY ("products_id") REFERENCES "products" ("id"),
  CONSTRAINT fk_products_orderitems_orderitem FOREIGN KEY ("order_items_id") REFERENCES "order_items" ("id")
);